### ISSUE TITLE
make docker image compatible with arm (raspberry pi)

### ISSUE THREAD

**Issue by Luxtech** [f100024/syncthing_exporter#19]
Is it possible to make this image compatible with ARM?
I tried running the docker image on my raspberry pi 4 and got the following error:
`syncthing_exporter    | standard_init_linux.go:219: exec user process caused: exec format error `

with the following docker-compose config:
```
version: "3.3"

services:
    syncthing_exporter:
      image: f100024/syncthing_exporter:0.2.4
      container_name: syncthing_exporter
      ports:
       - 9093:9093
      environment:
       SYNCTHING_URI: "http://127.0.0.1:8384/"
       SYNCTHING_TOKEN: "-----"
      restart: unless-stopped
```

I also tried it with the latest tag, but got the same error.

Thanks in advance
